# Generated by Django 2.1.7 on 2019-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimiento', '0002_auto_20190313_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='d_fecha_inicio_periodo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='d_fecha_regitro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='n_id',
            field=models.IntegerField(db_index=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='s_nombre',
            field=models.TextField(max_length=100, verbose_name='Nombre del Reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='s_parametro',
            field=models.TextField(blank=True, null=True, verbose_name='Parámetro'),
        ),
    ]
